[package]
name = "dive-into-rust-of-fcc"
version = "0.1.0"
authors = ["Little-Captain <coder.littlecaptain@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
